import { AuthGuard } from '@/components/ui/AuthGuard';
import type { Metadata, Viewport } from 'next';
import { Providers } from '@/components/layout/Providers';
import { BottomNav } from '@/components/ui/BottomNav';
import { ParticlesBg } from '@/components/ui/ParticlesBg';
import { AudioBar } from '@/components/audio/AudioBar';
import { Toaster } from '@/components/ui/Toast';
import { I18nProvider } from '@/components/ui/I18nProvider';
import { WelcomeTour } from '@/components/ui/WelcomeTour';
import '@/styles/globals.css';

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://noor-ai-v1.vercel.app';
const TITLE = 'نور AI — رفيقك الذكي في طريق الإيمان';
const DESCRIPTION =
  'منصة إسلامية ذكية متكاملة: القرآن الكريم بأصوات 6 قراء، مساعد AI للتفسير والفقه، مواقيت الصلاة، بوصلة القبلة، الأذكار، التسبيح الذكي، وغرف الإخوة. تجربة روحانية عصرية بين يديك.';

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: TITLE,
    template: '%s · نور AI',
  },
  description: DESCRIPTION,
  applicationName: 'نور AI',
  manifest: '/manifest.json',
  keywords: [
    'القرآن الكريم', 'مساعد إسلامي ذكي', 'تفسير القرآن', 'مواقيت الصلاة',
    'بوصلة القبلة', 'الأذكار', 'حصن المسلم', 'التسبيح', 'AI إسلامي',
    'Noor AI', 'تطبيق إسلامي', 'استماع القرآن', 'الفقه', 'الأحاديث',
  ],
  authors: [{ name: 'Sakhi Abderrahmane', url: 'https://www.snetprodz.com' }],
  creator: 'Sakhi Abderrahmane — ساخي عبد الرحمن',
  publisher: 'SNetProDz',
  alternates: { canonical: SITE_URL },
  category: 'religion',
  openGraph: {
    type: 'website',
    locale: 'ar_AR',
    url: SITE_URL,
    siteName: 'نور AI',
    title: TITLE,
    description: DESCRIPTION,
    // OG image is generated dynamically by app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: TITLE,
    description: DESCRIPTION,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, 'max-image-preview': 'large', 'max-snippet': -1 },
  },
  // favicon + apple icon are generated by app/icon.tsx and app/apple-icon.tsx
  appleWebApp: { capable: true, statusBarStyle: 'black-translucent', title: 'نور AI' },
  formatDetection: { telephone: false },
};

export const viewport: Viewport = {
  themeColor: '#030712',
  width: 'device-width',
  initialScale: 1,
  // accessibility: allow users to zoom (was maximumScale:1 + userScalable:false)
  maximumScale: 5,
  viewportFit: 'cover',
};

const JSON_LD = {
  '@context': 'https://schema.org',
  '@type': 'WebApplication',
  name: 'نور AI',
  alternateName: 'Noor AI',
  url: SITE_URL,
  description: DESCRIPTION,
  applicationCategory: 'LifestyleApplication',
  operatingSystem: 'Web, iOS, Android',
  inLanguage: 'ar',
  offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
  author: {
    '@type': 'Person',
    name: 'Sakhi Abderrahmane',
    alternateName: 'ساخي عبد الرحمن',
    url: 'https://www.snetprodz.com',
  },
  creator: {
    '@type': 'Person',
    name: 'Sakhi Abderrahmane',
    alternateName: 'ساخي عبد الرحمن',
  },
  publisher: {
    '@type': 'Organization',
    name: 'SNetProDz',
    url: 'https://www.snetprodz.com',
  },
  featureList: [
    'القرآن الكريم بأصوات 6 قراء',
    'مساعد ذكاء اصطناعي إسلامي',
    'مواقيت الصلاة وبوصلة القبلة',
    'الأذكار والتسبيح الذكي',
    'غرف الدردشة والمكالمات',
  ],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ar" dir="rtl">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Cairo:wght@300;400;500;600;700;800;900&family=Amiri:wght@400;700&family=Tajawal:wght@300;400;500;700;900&display=swap"
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(JSON_LD) }}
        />
      </head>
      <body>
        <div className="app-bg" />
        <ParticlesBg />
        <Providers>
          <I18nProvider>
            <WelcomeTour />
            <AuthGuard>
              <main style={{ position: 'relative', zIndex: 2, minHeight: '100dvh' }}>
                {children}
              </main>
            </AuthGuard>
            <AudioBar />
            <BottomNav />
            <Toaster />
          </I18nProvider>
        </Providers>
      </body>
    </html>
  );
}
